timApp/item/routes.py
"""Routes for document view."""
import dataclasses
import html
import time
from difflib import context_diff
from typing import Union, Any, ValuesView, Generator

import attr
import filelock
import sass
from flask import current_app
from flask import flash
from flask import redirect
from flask import render_template, make_response, Response, stream_with_context
from flask import request
from flask import session
from markupsafe import Markup
from sqlalchemy.orm import joinedload, defaultload

from timApp.answer.answers import add_missing_users_from_group, get_points_by_rule
from timApp.auth.accesshelper import (
    verify_view_access,
    verify_teacher_access,
    verify_seeanswers_access,
    get_doc_or_abort,
    verify_manage_access,
    AccessDenied,
    ItemLockedException,
)
from timApp.auth.auth_models import BlockAccess
from timApp.auth.get_user_rights_for_item import get_user_rights_for_item
from timApp.auth.sessioninfo import get_current_user_object, logged_in, save_last_page
from timApp.document.caching import check_doc_cache, set_doc_cache, refresh_doc_expire
from timApp.document.create_item import create_or_copy_item, create_citation_doc
from timApp.document.docentry import DocEntry, get_documents
from timApp.document.docinfo import DocInfo
from timApp.document.docparagraph import DocParagraph
from timApp.document.docrenderresult import DocRenderResult
from timApp.document.docsettings import DocSettings, get_minimal_visibility_settings
from timApp.document.document import (
    get_index_from_html_list,
    dereference_pars,
    Document,
)
from timApp.document.docviewparams import DocViewParams, ViewModelSchema
from timApp.document.hide_names import is_hide_names, force_hide_names
from timApp.document.post_process import post_process_pars, should_auto_read
from timApp.document.preloadoption import PreloadOption
from timApp.document.usercontext import UserContext
from timApp.document.viewcontext import (
    default_view_ctx,
    ViewRoute,
    ViewContext,
    viewmode_templates,
    DEFAULT_VIEWMODE_TEMPLATE,
)
from timApp.document.viewparams import ViewParams, ViewParamsSchema
from timApp.folder.folder import Folder
from timApp.folder.folder_view import try_return_folder
from timApp.item.block import BlockType, Block
from timApp.item.blockrelevance import BlockRelevance
from timApp.item.item import Item
from timApp.item.partitioning import (
    get_piece_size_from_cookie,
    decide_view_range,
    get_doc_version_hash,
    load_index,
    INCLUDE_IN_PARTS_CLASS_NAME,
    save_index,
    partition_texts,
    get_index_with_header_id,
    get_document_areas,
    RequestedViewRange,
    IndexedViewRange,
)
from timApp.item.scoreboard import get_score_infos_if_enabled
from timApp.item.tag import GROUP_TAG_PREFIX
from timApp.item.validation import has_special_chars
from timApp.messaging.messagelist.messagelist_utils import (
    MESSAGE_LIST_DOC_PREFIX,
    MESSAGE_LIST_ARCHIVE_FOLDER_PREFIX,
)
from timApp.peerreview.peerreview_utils import (
    generate_review_groups,
    get_reviews_for_user,
    check_review_grouping,
    PeerReviewException,
    is_peerreview_enabled,
)
from timApp.plugin.plugin import find_task_ids
from timApp.plugin.pluginControl import get_all_reqs
from timApp.readmark.readings import mark_all_read
from timApp.tim_app import app
from timApp.timdb.exceptions import PreambleException
from timApp.timdb.sqa import db
from timApp.user.groups import verify_group_view_access
from timApp.user.settings.style_utils import resolve_themes
from timApp.user.settings.styles import generate_style
from timApp.user.user import User, has_no_higher_right
from timApp.user.usergroup import (
    UserGroup,
    get_usergroup_eager_query,
    UserGroupWithSisuInfo,
)
from timApp.user.users import get_rights_holders_all
from timApp.user.userutils import DeletedUserException
from timApp.util.flask.requesthelper import (
    view_ctx_with_urlmacros,
    RouteException,
    NotExist,
)
from timApp.util.flask.responsehelper import add_no_cache_headers
from timApp.util.flask.responsehelper import (
    json_response,
    ok_response,
    get_grid_modules,
)
from timApp.util.flask.typedblueprint import TypedBlueprint
from timApp.util.timtiming import taketime
from timApp.util.utils import get_error_message, cache_folder_path
from timApp.util.utils import remove_path_special_chars, seq_to_str
from timApp.velp.velpgroups import set_default_velp_group_selected_and_visible
from tim_common.html_sanitize import sanitize_html

DEFAULT_RELEVANCE = 10

view_page = TypedBlueprint(
    "view_page",
    __name__,
    url_prefix="",
)

DocumentSlice = tuple[list[DocParagraph], IndexedViewRange]
ViewRange = Union[RequestedViewRange, IndexedViewRange]
FlaskViewResult = Union[Response, tuple[Any, int]]


def get_partial_document(doc: Document, view_range: ViewRange) -> DocumentSlice:
    all_pars = doc.get_paragraphs()

    # Handle common unrestricted case first.
    if view_range.is_full:
        return all_pars, IndexedViewRange(b=0, e=len(all_pars), par_count=len(all_pars))

    si = view_range.start_index
    ei = view_range.end_index
    if isinstance(view_range, RequestedViewRange):
        spid = view_range.start_par_id
        epid = view_range.end_par_id
    else:
        spid = None
        epid = None
    actual_start_index = None
    actual_end_index = None
    if si is not None and ei is not None:
        actual_start_index = si
        actual_end_index = ei
    elif si is not None:
        actual_start_index = si
    elif ei is not None:
        actual_end_index = ei
    else:
        for i, par in enumerate(all_pars):
            if par.get_id() == epid:
                actual_end_index = i
            if par.get_id() == spid:
                actual_start_index = i
            if actual_start_index is not None and actual_end_index is not None:
                break
    if actual_start_index is None:
        actual_start_index = 0
    if actual_end_index is None:
        actual_end_index = (
            len(all_pars)
            if view_range.size is None
            else actual_start_index + view_range.size
        )
    pars = all_pars[actual_start_index:actual_end_index]
    return pars, IndexedViewRange(
        b=actual_start_index, e=actual_end_index, par_count=len(all_pars)
    )


def get_document(doc_info: DocInfo, view_range: ViewRange) -> DocumentSlice:
    doc = doc_info.document
    doc.preload_option = PreloadOption.all
    return get_partial_document(doc, view_range)


@view_page.get("/show_slide/<path:doc_path>")
def show_slide(doc_path):
    return view(doc_path, ViewRoute.ShowSlide)


@view_page.get("/view/<path:doc_path>")
def view_document(doc_path):
    taketime("route view begin")
    ret = view(doc_path, ViewRoute.View)
    taketime("route view end")
    return ret


@view_page.get("/teacher/<path:doc_path>")
def teacher_view(doc_path):
    return view(doc_path, ViewRoute.Teacher)


@view_page.get("/velp/<path:doc_path>")
def velp_view(doc_path):
    return view(doc_path, ViewRoute.Velp)


@view_page.get("/answers/<path:doc_path>")
def see_answers_view(doc_path):
    return view(doc_path, ViewRoute.Answers)


@view_page.get("/lecture/<path:doc_path>")
def lecture_view(doc_path):
    return view(doc_path, ViewRoute.Lecture)


@view_page.get("/review/<path:doc_name>")
def review_view(doc_name):
    return view(doc_name, ViewRoute.Review)


@view_page.get("/slide/<path:doc_path>")
def slide_view(doc_path):
    return view(doc_path, ViewRoute.Slide, render_doc=False)


@view_page.get("/par_info/<int:doc_id>/<par_id>")
def par_info(doc_id, par_id):
    doc = get_doc_or_abort(doc_id)
    verify_view_access(doc)
    for o in doc.owners:
        o.load_personal_user()
    par_name = doc.document.get_closest_paragraph_title(par_id)
    return json_response(
        {
            "item": doc,
            "par_name": par_name,
        }
    )


@view_page.get("/docViewInfo/<path:doc_name>")
def doc_access_info(doc_name):
    doc_info = DocEntry.find_by_path(doc_name, fallback_to_id=True)
    if not doc_info:
        raise NotExist()

    can_access = False
    try:
        view_access = verify_view_access(doc_info, require=False, check_duration=True)
        can_access = view_access is not None
    except ItemLockedException as ile:
        view_access = ile.access

    return json_response(
        {"can_access": can_access, "right": view_access}, date_conversion=True
    )


@attr.s(auto_attribs=True)
class ItemWithRights:
    i: Item
    rights: list[BlockAccess]

    def to_json(self):
        return {
            **self.i.to_json(),
            "grouprights": self.rights,
        }


@view_page.get("/getItems")
def items_route(
    folder: str | None = None,
    folder_id: int | None = None,
    recursive: bool = False,
    include_rights: bool = False,
):
    if folder is not None:
        f = Folder.find_by_path(folder)
    elif folder_id is not None:
        f = Folder.get_by_id(folder_id)
    else:
        raise RouteException()
    if not f:
        raise NotExist("Folder not found.")
    if not f.is_root():
        verify_view_access(f)

    items = get_items(f.path, recurse=recursive)
    if include_rights:
        u = get_current_user_object()
        rights = get_rights_holders_all(
            [i.id for i in items if u.has_manage_access(i)], order_by=BlockAccess.type
        )
        items = [ItemWithRights(i, rights[i.id]) for i in items]
    return json_response(items)


@view_page.get("/view")
def index_page():
    save_last_page()
    return render_template("index.jinja2", items=get_items(""), item=Folder.get_root())


@view_page.get("/generateCache/<path:doc_path>")
def gen_cache(
    doc_path: str,
    same_for_all: bool = False,
    force: bool = False,
    print_diffs: bool = False,
    group: str | None = None,
):
    """Pre-generates document cache for the users with non-expired rights.

timApp/slide/routes.py
import json

from timApp.auth.accesshelper import get_doc_or_abort, verify_manage_access
from timApp.slide.slidestatus import SlideStatus
from timApp.timdb.sqa import db
from timApp.util.flask.responsehelper import json_response, ok_response
from timApp.util.flask.typedblueprint import TypedBlueprint

slide_bp = TypedBlueprint(
    "slide",
    __name__,
    url_prefix="",
)


@slide_bp.get("/getslidestatus")
def getslidestatus(doc_id: int):
    status: SlideStatus = SlideStatus.query.filter_by(doc_id=doc_id).first()
    st = status.status if status else None
    return json_response(json.loads(st))


@slide_bp.post("/setslidestatus")
def setslidestatus(
    doc_id: int,
    indexf: int,
    indexh: int,
    indexv: int,
):
    d = get_doc_or_abort(doc_id)
    verify_manage_access(d)
    s = SlideStatus(
        doc_id=doc_id,
        status=json.dumps(dict(indexf=indexf, indexh=indexh, indexv=indexv)),
    )
    db.session.merge(s)
    db.session.commit()
    return ok_response()

timApp/templates/base.jinja2
{% import 'macros.jinja2' as m -%}

{% set lecture_mode = route == "lecture" %}
{% set is_lecture_info = request.endpoint == 'lecture.show_lecture_info' %}
{% set show_lecture_menu = lecture_info.in_lecture or lecture_mode or is_lecture_info %}

{# Set default column widths if they are not defined in a child template #}
{% set col_1_lg = col_1_lg|default(2) %}
{% set col_2_lg = col_2_lg|default(8) %}
{% set col_3_lg = col_3_lg|default(2) %}
{% set col_m_lg = col_m_lg|default(12) %} {# col_m_* must be even #}

{% set col_1_md = col_1_md|default(2) %}
{% set col_2_md = col_2_md|default(8) %}
{% set col_3_md = col_3_md|default(2) %}
{% set col_m_md = col_m_md|default(12) %}

{% set col_1_sm = col_1_sm|default(2) %}
{% set col_2_sm = col_2_sm|default(10) %}
{% set col_3_sm = col_3_sm|default(0) %}
{% set col_m_sm = col_m_sm|default(12) %}

{% set col_1_xs = col_1_xs|default(0) %}
{% set col_2_xs = col_2_xs|default(12) %}
{% set col_3_xs = col_3_xs|default(0) %}
{% set col_m_xs = col_m_xs|default(12) %}

<!DOCTYPE html>
<html lang="{{ locale }}">
<head>
    {% block head %}
        <base href="{{ request.path }}">
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <meta name="description" content="TIM - The Interactive Material."/>
        <meta name="keywords" content="tim,interactive,material"/>

        <link href="{{ url_for('static', filename='images/favicon.ico') }}" rel="shortcut icon" type="image/x-icon"/>
        <meta name="google-site-verification" content="GHYGje2NiYlQM66xyggsnzQht1OHSgtv_9baHbFIklU"/>
        <script>
            var homeOrganization = {{ config.HOME_ORGANIZATION|tojson }};
            var IS_TESTING = {{ config.TESTING|tojson }};
            var ANGULARMODULES = [];
            var JSMODULES = [];

            {% if show_lecture_menu %}JSMODULES.push("lectureMenu");{% endif %}
            {% if is_lecture_info %}JSMODULES.push("lectureInfo");{% endif %}

            var userPrefs = {{ prefs|tojson }};
            var current_user = {{ current_user.to_json(full=True)|tojson }};
            var other_users = {{ other_users|tojson }};
            var bookmarks = {{ bookmarks|tojson }};
            var locale = {{locale|tojson}};
            var lectureInfo = {{lecture_info|tojson}};
            var footerDocs = {
                privacyNotice: {{ config.PRIVACY_NOTICE_DOC|tojson }},
                accessibilityStatement: {{ config.ACCESSIBILITY_STATEMENT_DOC|tojson }}
            };

            var layout = {};
            layout.col_1_lg = {{col_1_lg|tojson}};
            layout.col_2_lg = {{col_2_lg|tojson}};
            layout.col_3_lg = {{col_3_lg|tojson}};
            layout.col_m_lg = {{col_m_lg|tojson}};
            layout.col_1_md = {{col_1_md|tojson}};
            layout.col_2_md = {{col_2_md|tojson}};
            layout.col_3_md = {{col_3_md|tojson}};
            layout.col_m_md = {{col_m_md|tojson}};
            layout.col_1_sm = {{col_1_sm|tojson}};
            layout.col_2_sm = {{col_2_sm|tojson}};
            layout.col_3_sm = {{col_3_sm|tojson}};
            layout.col_m_sm = {{col_m_sm|tojson}};
            layout.col_1_xs = {{col_1_xs|tojson}};
            layout.col_2_xs = {{col_2_xs|tojson}};
            layout.col_3_xs = {{col_3_xs|tojson}};
            layout.col_m_xs = {{col_m_xs|tojson}};

            var config = {};
            config.gitLastestCommitTimestamp = {{config.GIT_LATEST_COMMIT_TIMESTAMP|tojson}};
            config.helpEmail = {{config.HELP_EMAIL|tojson}};
            config.gitBranch = {{config.GIT_BRANCH|tojson}};
            config.hakaEnabled = {{config.HAKA_ENABLED|tojson}};
            config.emailRegistrationEnabled = {{config.EMAIL_REGISTRATION_ENABLED|tojson}};
            config.simpleEmailLogin = {{config.SIMPLE_EMAIL_LOGIN|tojson}};
            config.simpleLoginUseStudyInfoMessage = {{config.SIMPLE_LOGIN_USE_STUDY_INFO_MESSAGE|tojson}};
            config.minPasswordLength = {{config.MIN_PASSWORD_LENGTH|tojson}};
            config.hosts = {{config.HOSTS|tojson}};
            config.messageListsEnabled = {{config.MESSAGE_LISTS_ENABLED|tojson}};
        </script>
        {{ angularscripts|safe }}
        {% if not override_theme %}
            <link rel="stylesheet" data-style-origin="user-prefs-style" href="/{{ prefs.style_path }}">
        {% endif %}

        <script type="text/x-mathjax-config">
            MathJax.Hub.Config({
                skipStartupTypeset: true
            });
        </script>
        <title>{% block title %}{% endblock %} - TIM</title>
    {% endblock %}
    <style data-style-origin="user-prefs-custom">
        {{ prefs.custom_css }}
    </style>
</head>
<body>
{% block body %}
{% if request.user_agent.browser == 'msie' %}
<div style="text-align: center; border: 2px solid red; padding: 1em;">
    <p>TIM ei toimi Internet Explorer -selaimella. Siirry käyttämään modernia selainta, kuten Firefoxia tai Chromea.</p>

    <p>TIM does not work with Internet Explorer. Please switch to a modern browser such as Firefox or Chrome.</p>
</div>
{% endif %}
<tim-root>
<{% block mainctrl %}div{% endblock %} style="flex: 1">
    <div ng-init="$ctrl = $parent.$ctrl" class="container-fluid">
        <div class="row hidden-print" ng-cloak>
            <div class="col-lg-{{ col_1_lg }}
                        col-md-{{ col_1_md }}
                        col-xs-{{ col_1_xs }}
                        col-sm-{{ col_1_sm }}">
                <tim-sidebar-menu></tim-sidebar-menu>
            </div>
            <div class="col-lg-{{ col_2_lg }}
                        col-md-{{ col_2_md }}
                        col-xs-{{ col_2_xs }}
                        col-sm-{{ col_2_sm }}">
                <tim-site-header></tim-site-header>
            </div>
            <div class="col-lg-{{ col_3_lg }}
                        col-md-{{ col_3_md }}
                        col-xs-{{ col_3_xs }}
                        col-sm-{{ col_3_sm }}">
                <div class="right-fixed-side">
                    {% block rightside %}{% endblock %}
                </div>
            </div>
        </div>
        <div class="row" ng-if="!$ctrl.hide.messages" ng-cloak>
            <div class="col-lg-{{ col_2_lg }} col-lg-offset-{{ col_1_lg }}
                        col-md-{{ col_2_md }} col-md-offset-{{ col_1_md }}
                        col-xs-{{ col_2_xs }} col-xs-offset-{{ col_1_xs }}
                        col-sm-{{ col_2_sm }} col-sm-offset-{{ col_1_sm }}">
                {% for n in global_notifications %}
                    <div class="global-notification alert alert-info">
                        <i class="glyphicon glyphicon-info-sign"></i> {{ n|safe }}
                    </div>
                {% endfor %}
                <tim-message-view></tim-message-view>
                {% with messages = get_flashed_messages(with_categories=True) %}
                    {% if messages %}
                        {% for category, message in messages %}
                            <div class="alert alert-info">
                                <i class="glyphicon glyphicon-info-sign"></i>
                                {% if category == 'raw' %}
                                    {{ message|safe }}
                                {% else %}
                                    {{ message }}
                                {% endif %}
                            </div>
                        {% endfor %}
                    {% endif %}
                {% endwith %}
            </div>
        </div>
        <div class="row" ng-if="!$ctrl.hide.header" ng-cloak>
            <div class="col-lg-{{ col_2_lg }} col-lg-offset-{{ col_1_lg }}
                        col-md-{{ col_2_md }} col-md-offset-{{ col_1_md }}
                        col-xs-{{ col_2_xs }} col-xs-offset-{{ col_1_xs }}
                        col-sm-{{ col_2_sm }} col-sm-offset-{{ col_1_sm }}">
                <div id="header" class="hidden-print">
                    <tim-header></tim-header>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-{{ col_2_lg }} col-lg-offset-{{ col_1_lg }}
                        col-md-{{ col_2_md }} col-md-offset-{{ col_1_md }}
                        col-xs-{{ col_2_xs }} col-xs-offset-{{ col_1_xs }}
                        col-sm-{{ col_2_sm }} col-sm-offset-{{ col_1_sm }}">
                <div class="row main-content">
                    <div class="col-lg-{{ col_m_lg }} col-lg-offset-{{ (12 - col_m_lg) // 2 }}
                                col-md-{{ col_m_md }} col-md-offset-{{ (12 - col_m_md) // 2 }}
                                col-xs-{{ col_m_xs }} col-xs-offset-{{ (12 - col_m_xs) // 2 }}
                                col-sm-{{ col_m_sm }} col-sm-offset-{{ (12 - col_m_sm) // 2 }}">
                        <div class="material">
                            {% if show_lecture_menu %}
                                <tim-lecture-menu></tim-lecture-menu>
                            {% endif %}
                            {% block content %}{% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</{{ self.mainctrl() }}>
<tim-footer ng-if="!$parent.$ctrl.hide.footer"></tim-footer>
</tim-root>
{% endblock %}
<div class="device-xs visible-xs-block"></div>
<div class="device-sm visible-sm-block"></div>
<div class="device-md visible-md-block"></div>
<div class="device-lg visible-lg-block"></div>
<tim-dialog-container></tim-dialog-container>
</body>
</html>

timApp/templates/create_new.jinja2
{% extends "base.jinja2" %}
{% block title %}This page does not yet exist.{% endblock %}
{% block content %}
    <p class="errormsg">{{ message or self.title() }}</p>
    {% if session.user_id %}
        {% if show_create_new %}
            <bootstrap-panel title="Create a new document here">
                <create-item
                        item-type="document"
                        full-path="{{ new_item }}"
                        force="true"
                        {% if forced_template %}
                        template="{{ forced_template }}">
                        {% endif %}
                </create-item>
            </bootstrap-panel>
{#
            <bootstrap-panel title="Create a new folder here">
                <create-item item-type="folder" full-path="{{ new_item }}"></create-item>
            </bootstrap-panel>
#}
        {% else %}
            You cannot create documents or folders here.
        {% endif %}
    {% else %}
        To create a new document or a folder, log in.
    {% endif %}
    {% if found_item %}
        <a href="/view/{{ found_item.path }}">To the first existing item ({{ found_item.title }}) in your search.</a>
    {% else %}
        <a href="{{ url_for('view_page.index_page') }}">To the index.</a>
    {% endif %}
{% endblock %}

timApp/templates/dumbo_html_error.jinja2
{% extends "error.jinja2" %}
{% block content %}
<p>
    The markdown server failed to render markdown to HTML. This usually means that the mathematical formulas
    in this document are still being processed. This page will refresh periodically. Please wait.
</p>
<script>
    document.addEventListener("DOMContentLoaded", function () {
        window.location.reload();
    });
</script>
{% endblock %}

timApp/templates/duration_unlock.jinja2
{% extends 'item.jinja2' %}
{% block head %}
    {{ super() }}
    {% if view_settings %}
        <script class="global-vars">
            var docSettings = {};
            var exam_mode = {{ view_settings.exam_mode|tojson }};
            var hide_sidemenu = {{ view_settings.hide_sidemenu|tojson }};
        </script>
   {% endif %}
{% endblock %}
{% block content %}
    <div class="alert alert-warning">
        <i class="glyphicon glyphicon-warning-sign"></i>
        {% if msg %}
            {{ msg }}
        {% elif access.unlockable %}
            You are about to access a time-limited {{ item_type }}.
            After you click Unlock, your access to this {{ item_type }} will be removed in under {{ access.duration_now | timtimedelta }}.
        {% elif access.require_confirm %}
            You can unlock this item only after your permission is confirmed.
            Please refresh this page after a while (e.g. 20 seconds) to recheck your confirmation.
        {% elif access.duration_expired %}
            You cannot unlock this item anymore (deadline expired {{ access.duration_to | timreldatetime }}).
        {% elif access.duration_future %}
            You can unlock this item in {{ access.duration_from | timreldatetime }}.
            Please refresh this page after that time.
        {% elif access.expired %}
            Your access to this item has expired {{ access.accessible_to | timreldatetime }}.
        {% elif access.future %}
            <tim-access-countdown bind-wait-time="{{ access.time_until_access_start }}"></tim-access-countdown>
        {% else %}
            You don't have access to this item.
        {% endif %}
    </div>
    {% if next_doc %}
        <div class="text-center">
            <a href="/view/{{ next_doc.path }}?unlock=true" class="timButton">Go to the next document</a>
        </div>
    {% endif %}
    {% if access.unlockable %}
        <div class="text-center">
            <a href="/view/{{ item.path }}?unlock=true" class="timButton">Unlock</a>
        </div>
    {% endif %}
{% endblock %}

timApp/templates/generic_html_error_standalone.jinja2
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="TIM - The Interactive Material."/>
    <meta name="keywords" content="tim,interactive,material"/>
    <link href="/static/images/favicon.ico" rel="shortcut icon" type="image/x-icon"/>
    <title>{% if title %}{{ title }}{% else %}Failed to load page - TIM{% endif %}</title>
</head>
<body>
<a href="/">
    <img alt="TIM - The Interactive Material."
         src="/static/images/tim-logo_42height.png"
         title="Go to front page"/>
</a>
<img alt="Jyväskylän yliopisto" class="pull-right" height="42" src="/static/images/jyulogo.png"/>
<p class="text-center">{{ description }}</p>
{% if auto_refresh %}
    <p class="text-center">This page will refresh periodically. Please wait.</p>
{% endif %}
<h4>Error details</h4>
<pre class="small">{{ error }}</pre>
{% if auto_refresh %}
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            setTimeout(function () { window.location.reload(); }, 1000);
        });
    </script>
{% endif %}
</body>
</html>

timApp/templates/index.jinja2
{% extends "folder.jinja2" %}
{% block title %}{{'{} {}'.format(item.title, '({})'.format(item.location) if item.location else '')}}{% endblock %}
{% block head %}
    {{ super() }}

    <script>
        var items = {{ items | tojson }};
    </script>
{% endblock %}

{% set col_m_lg = 10 %}

{% block content %}
    <tim-index></tim-index>
{% endblock %}

timApp/templates/item.jinja2
{% extends 'base.jinja2' %}
{% block head %}
    {{ super() }}
    <script class="global-vars">
        var curr_item = {{item|tojson}};
        var breadcrumbs = {{item.parents_to_root_eager|tojson}};
    </script>
{% endblock %}

timApp/templates/lectureInfo.jinja2
{% extends "item.jinja2" %}
{% block title %}Lecture info{% endblock %}
{% block head %}
    {{ super() }}

    <script>
        var lecture = {{lecture|tojson}};
    </script>

{% endblock %}
{% block content %}
<tim-lecture-info></tim-lecture-info>
{% endblock %}

timApp/templates/loginpage.jinja2
{% extends "base.jinja2" %}
{% block title %}Login{% endblock %}
{% block head %}
    {{ super() }}
    {% if view_settings %}
        <script class="global-vars">
            var docSettings = {};
            var exam_mode = {{ view_settings.exam_mode|tojson }};
            var hide_sidemenu = {{ view_settings.hide_sidemenu|tojson }};
        </script>
   {% endif %}
{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
            <p class="text-center">
                {{ text|default(request.args.logintext)|default('Login is required for this document. Please use the above button to log in.') }}
            </p>
        </div>
    </div>
{% endblock %}

timApp/templates/macros.jinja2
{% macro scss(name) -%}
    {% assets depends=(
"stylesheets/*.scss",
"stylesheets/**/*.scss",
),
 filters="libsass",
 output="{}.css".format(name),
  name|string + ".scss" %}
        <link rel="stylesheet" href="{{ ASSET_URL }}">
    {% endassets %}
{%- endmacro %}

timApp/templates/show_slide.jinja2
{% extends 'view_html.jinja2' %}

{% block body %}
    <tim-view>
    <div class="reveal" style="visibility: hidden">
        <div class="slides paragraphs">
            {{ doc_content|safe }}
        </div>
    </div>
    </tim-view>
{% endblock %}